-- RETIRED: do not use the old header-derived submission function.
--
-- The previous implementation read CF-Connecting-IP during the second
-- Edge-Function-to-PostgREST hop and could hash a backend egress address.
-- Use supabase-ip-flow-v2.sql, deploy submit-drop-verified, then run
-- supabase-ip-flow-v2-cleanup.sql.
